/*
 * StyleAboutBox.java
 */

package style;
import java.util.logging.Level;
import java.util.logging.Logger;
import style.Bases.*;
import java.sql.*;

import org.jdesktop.application.Action;

public class CargaContacto extends javax.swing.JDialog {

    public CargaContacto(java.awt.Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
    }

    @Action public void closeAboutBox() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        eNombre = new javax.swing.JLabel();
        cNombre = new javax.swing.JTextField();
        cApellido = new javax.swing.JTextField();
        eApellido = new javax.swing.JLabel();
        eCelular = new javax.swing.JLabel();
        cCel = new javax.swing.JTextField();
        campoPrestamo = new javax.swing.JTextField();
        eDireccion = new javax.swing.JLabel();
        cDireccion = new javax.swing.JTextField();
        cCorreo = new javax.swing.JTextField();
        dni = new javax.swing.JLabel();
        eCobrador = new javax.swing.JLabel();
        lCobrador = new javax.swing.JComboBox();
        ePlan = new javax.swing.JLabel();
        campoPlanCantidadCuotas = new javax.swing.JTextField();
        eDe = new javax.swing.JLabel();
        campoPlanMontoCuota = new javax.swing.JTextField();
        observ = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cParticuilar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoMonto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(style.StyleApp.class).getContext().getResourceMap(CargaContacto.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(300, 79));
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(style.StyleApp.class).getContext().getActionMap(CargaContacto.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N

        botonAceptar.setText(resourceMap.getString("botonAceptar.text")); // NOI18N
        botonAceptar.setName("botonAceptar"); // NOI18N
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        eNombre.setText(resourceMap.getString("eNombre.text")); // NOI18N
        eNombre.setName("eNombre"); // NOI18N

        cNombre.setText(resourceMap.getString("cNombre.text")); // NOI18N
        cNombre.setName("cNombre"); // NOI18N

        cApellido.setName("cApellido"); // NOI18N

        eApellido.setText(resourceMap.getString("eApellido.text")); // NOI18N
        eApellido.setName("eApellido"); // NOI18N

        eCelular.setText(resourceMap.getString("eCelular.text")); // NOI18N
        eCelular.setName("eCelular"); // NOI18N

        cCel.setName("cCel"); // NOI18N

        campoPrestamo.setName("campoPrestamo"); // NOI18N

        eDireccion.setText(resourceMap.getString("eDireccion.text")); // NOI18N
        eDireccion.setName("eDireccion"); // NOI18N

        cDireccion.setName("cDireccion"); // NOI18N

        cCorreo.setName("cCorreo"); // NOI18N

        dni.setText(resourceMap.getString("dni.text")); // NOI18N
        dni.setName("dni"); // NOI18N

        eCobrador.setText(resourceMap.getString("eCobrador.text")); // NOI18N
        eCobrador.setName("eCobrador"); // NOI18N

        lCobrador.setName("lCobrador"); // NOI18N
        lCobrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lCobradorActionPerformed(evt);
            }
        });
        BCobradores cobrador = new BCobradores();
        cobrador.ConectarSQL();
        try {
            cobrador.getNombreApellido(lCobrador);
        }catch (SQLException ex ){lCobrador.addItem("Error");}
        cobrador.CerrarSQL();

        ePlan.setText(resourceMap.getString("ePlan.text")); // NOI18N
        ePlan.setName("ePlan"); // NOI18N

        campoPlanCantidadCuotas.setText(resourceMap.getString("campoPlanCantidadCuotas.text")); // NOI18N
        campoPlanCantidadCuotas.setName("campoPlanCantidadCuotas"); // NOI18N

        eDe.setText(resourceMap.getString("eDe.text")); // NOI18N
        eDe.setName("eDe"); // NOI18N

        campoPlanMontoCuota.setText(resourceMap.getString("campoPlanMontoCuota.text")); // NOI18N
        campoPlanMontoCuota.setName("campoPlanMontoCuota"); // NOI18N
        campoPlanMontoCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPlanMontoCuotaActionPerformed(evt);
            }
        });
        campoPlanMontoCuota.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                campoPlanMontoCuotaInputMethodTextChanged(evt);
            }
        });

        observ.setText(resourceMap.getString("observ.text")); // NOI18N
        observ.setName("observ"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        cParticuilar.setName("cParticuilar"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        campoMonto.setEditable(false);
        campoMonto.setText(resourceMap.getString("campoMonto.text")); // NOI18N
        campoMonto.setName("campoMonto"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(eNombre)
                                        .addComponent(eCelular)))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(eDireccion)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addComponent(cCel)
                                .addComponent(cNombre)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cParticuilar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(eCobrador)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(eApellido)
                        .addComponent(ePlan)
                        .addComponent(dni)
                        .addComponent(observ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(closeButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(campoPlanCantidadCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eDe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(campoPlanMontoCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(cCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(campoPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eNombre)
                            .addComponent(eApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eCelular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eDireccion))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cCel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(observ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dni)
                            .addComponent(cDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(campoPlanCantidadCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eDe)
                            .addComponent(campoPlanMontoCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ePlan)
                        .addComponent(jLabel1)
                        .addComponent(cParticuilar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eCobrador)
                    .addComponent(lCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(campoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(closeButton))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName(resourceMap.getString("aboutBox.AccessibleContext.accessibleName")); // NOI18N
        getAccessibleContext().setAccessibleDescription(resourceMap.getString("aboutBox.AccessibleContext.accessibleDescription")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed

    BClientes cliente = new BClientes ();
    BCobradores cobradores = new BCobradores ();
    BCuotas cuotas = new BCuotas ();
    BDeuda deuda = new BDeuda ();
    BPago pago = new BPago ();
    BCaja caja = new BCaja ();
    
    String boludez = (String) lCobrador.getSelectedItem();
    String[] arr = new String [2];
    arr = boludez.split(" ");

    cliente.ConectarSQL();
    cobradores.ConectarSQL();
    cuotas.ConectarSQL();
    deuda.ConectarSQL();
    pago.ConectarSQL();
    caja.ConectarSQL();
    
    // hay q agregar el campo cParticular con ese nombre a la interfaz!!! 
    cliente.insertarCliente(cNombre.getText(), cApellido.getText(), cCel.getText(), "", cDireccion.getText(), cCorreo.getText(),cParticuilar.getText());
        try {
            deuda.crearDeuda((Double.valueOf(campoPlanMontoCuota.getText()))*(Integer.valueOf(campoPlanCantidadCuotas.getText())), Integer.valueOf(campoPlanCantidadCuotas.getText()), cliente.getIdFromNomAp(cNombre.getText(), cApellido.getText()));
            cuotas.insertarCuotas(Integer.valueOf(campoPlanCantidadCuotas.getText()), deuda.fechaGenerada(deuda.getIdDeudas(cliente.getIdFromNomAp(cNombre.getText(), cApellido.getText()))), Double.valueOf(campoPlanMontoCuota.getText()), deuda.getIdDeudas(cliente.getIdFromNomAp(cNombre.getText(), cApellido.getText())));
            pago.agregarPago(cliente.getIdFromNomAp(cNombre.getText(), cApellido.getText()),deuda.getIdDeudas(cliente.getIdFromNomAp(cNombre.getText(), cApellido.getText())), 0, deuda.fechaGenerada(deuda.getIdDeudas(cliente.getIdFromNomAp(cNombre.getText(), cApellido.getText()))), cobradores.getIdFromNomAp(arr[0], arr[1]));
            /*
             * monto total de deuda
             * (Double.valueOf(campoPlanMontoCuota.getText()))*(Integer.valueOf(campoPlanCantidadCuotas.getText())
             */

            caja.insertarEgreso("Prestamo a "+cNombre.getText() + " "+cApellido.getText(), Double.valueOf(campoPrestamo.getText()));

        } catch (SQLException ex) {
            Logger.getLogger(CargaContacto.class.getName()).log(Level.SEVERE, null, ex);
        }

    cliente.CerrarSQL();
    cobradores.CerrarSQL();
    cuotas.CerrarSQL();
    deuda.CerrarSQL();
    pago.CerrarSQL();

    cNombre.setText("");
    cApellido.setText("");
    cCel.setText("");
    campoPrestamo.setText("");
    cDireccion.setText("");
    cCorreo.setText("");
    campoPlanCantidadCuotas.setText("");
    campoPlanMontoCuota.setText("");
    cParticuilar.setText("");
    
    dispose();
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void lCobradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lCobradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lCobradorActionPerformed

private void campoPlanMontoCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPlanMontoCuotaActionPerformed
// TODO add your handling code here:
    int cuotas = Integer.valueOf(campoPlanCantidadCuotas.getText());
    double monto = Double.valueOf(campoPlanMontoCuota.getText());
    campoMonto.setText(String.valueOf(monto*cuotas));
}//GEN-LAST:event_campoPlanMontoCuotaActionPerformed

private void campoPlanMontoCuotaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_campoPlanMontoCuotaInputMethodTextChanged
// TODO add your handling code here:
    int cuotas = Integer.valueOf(campoPlanCantidadCuotas.getText());
    double monto = Double.valueOf(campoPlanMontoCuota.getText());
    campoMonto.setText(String.valueOf(monto*cuotas));
}//GEN-LAST:event_campoPlanMontoCuotaInputMethodTextChanged
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JTextField cApellido;
    private javax.swing.JTextField cCel;
    private javax.swing.JTextField cCorreo;
    private javax.swing.JTextField cDireccion;
    private javax.swing.JTextField cNombre;
    private javax.swing.JTextField cParticuilar;
    private javax.swing.JTextField campoMonto;
    private javax.swing.JTextField campoPlanCantidadCuotas;
    private javax.swing.JTextField campoPlanMontoCuota;
    private javax.swing.JTextField campoPrestamo;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel dni;
    private javax.swing.JLabel eApellido;
    private javax.swing.JLabel eCelular;
    private javax.swing.JLabel eCobrador;
    private javax.swing.JLabel eDe;
    private javax.swing.JLabel eDireccion;
    private javax.swing.JLabel eNombre;
    private javax.swing.JLabel ePlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox lCobrador;
    private javax.swing.JLabel observ;
    // End of variables declaration//GEN-END:variables
    
}
