/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Contraseña.java
 *
 * Created on 20-dic-2011, 23:58:20
 */

package style;
import javax.swing.*;
/**
 *
 * @author Tony
 */
public class Contraseña extends javax.swing.JFrame {

    /** Creates new form Contraseña */
    public Contraseña() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entrar = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(style.StyleApp.class).getContext().getResourceMap(Contraseña.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        entrar.setText(resourceMap.getString("entrar.text")); // NOI18N
        entrar.setName("entrar"); // NOI18N
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        getContentPane().add(entrar);
        entrar.setBounds(161, 240, 90, 23);

        pass.setText(resourceMap.getString("pass.text")); // NOI18N
        pass.setName("pass"); // NOI18N
        getContentPane().add(pass);
        pass.setBounds(130, 210, 150, 20);

        Fondo.setIcon(resourceMap.getIcon("Fondo.icon")); // NOI18N
        Fondo.setText(resourceMap.getString("Fondo.text")); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(433, 320));
        Fondo.setMinimumSize(new java.awt.Dimension(433, 320));
        Fondo.setName("Fondo"); // NOI18N
        Fondo.setPreferredSize(new java.awt.Dimension(433, 320));
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 433, 300);
        Fondo.getAccessibleContext().setAccessibleParent(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
       if (String.valueOf(pass.getPassword()).compareTo("elsecreto")==0)
            {

            Main ventana = new Main();
            ventana.setVisible(true);
            this.dispose();



            }

        else { pass.setText("");
        }
        
    }//GEN-LAST:event_entrarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton entrar;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables
         
       
}
