/*
 * StyleAboutBox.java
 */

package style;

import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.application.Action;
import style.Bases.BClientes;
import style.Bases.BDeuda;

public class HistorialPagos extends javax.swing.JDialog {

    public HistorialPagos(java.awt.Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
    }
    
    public HistorialPagos(java.awt.Frame parent, int idCliente) throws SQLException {
        super(parent);
        initComponents();
        indexCliente = idCliente;
        getRootPane().setDefaultButton(closeButton);
        
            vaciarTabla(jTable1);

            BDeuda deuda = new BDeuda();
            deuda.ConectarSQL();
            
            int cantidadDeDeudas = deuda.getCantidadDeudas(idCliente);
            for(int i=0;i < cantidadDeDeudas;i++){
                jcbDeudas.addItem(i);
            }
            int idDeuda = deuda.getIdUltimaDeuda(idCliente);
            deuda.llenarPagos(idDeuda, jTable1);
            
    }

    @Action public void closeAboutBox() {
        vaciarTabla(jTable1);
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        imprimir = new javax.swing.JButton();
        jcbDeudas = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(style.StyleApp.class).getContext().getResourceMap(HistorialPagos.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(style.StyleApp.class).getContext().getActionMap(HistorialPagos.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Pago", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTable1.columnModel.title0")); // NOI18N
        jTable1.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTable1.columnModel.title1")); // NOI18N

        imprimir.setText(resourceMap.getString("imprimir.text")); // NOI18N
        imprimir.setName("imprimir"); // NOI18N
        imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirActionPerformed(evt);
            }
        });

        jcbDeudas.setName("jcbDeudas"); // NOI18N
        jcbDeudas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDeudasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(imprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jcbDeudas, 0, 280, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbDeudas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imprimir)
                    .addComponent(closeButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirActionPerformed
        try {
            BClientes bcli = new BClientes();
            bcli.ConectarSQL();

            MessageFormat header = null;
            try {
                header = new MessageFormat(bcli.getDatosCliente(indexCliente)[0]+" "+bcli.getDatosCliente(indexCliente)[1]);
            } catch (SQLException ex) {
                Logger.getLogger(HistorialPagos.class.getName()).log(Level.SEVERE, null, ex);
            }
            jTable1.print(JTable.PrintMode.FIT_WIDTH,header,null);
        // TODO add your handling code here:
        } catch (PrinterException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_imprimirActionPerformed

private void jcbDeudasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDeudasActionPerformed
    vaciarTabla(jTable1);
    BDeuda deuda = new BDeuda();
    deuda.ConectarSQL();
    int numeroDeuda = (Integer) jcbDeudas.getSelectedItem();
    
    try{
    int[] indexDeuda = deuda.getIdUltimaDeuda(indexCliente,numeroDeuda+1);
    deuda.llenarPagos(indexDeuda[numeroDeuda], jTable1);
    } catch(SQLException e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jcbDeudasActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton imprimir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jcbDeudas;
    // End of variables declaration//GEN-END:variables
    private int indexCliente;


    public void vaciarTabla(javax.swing.JTable tabla){
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        model.setRowCount(0);
    }

}
