/*
 * StyleAboutBox.java
 */

package style;

import org.jdesktop.application.Action;
import style.Bases.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class NuevoPlan extends javax.swing.JDialog {

    public NuevoPlan(java.awt.Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
    }
    
    public NuevoPlan(java.awt.Frame parent,String nombre,String apellido,String direccion,String telefono,String celular,String correo){
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
        cNombre.setText(nombre);
        cApellido.setText(apellido);
        cDireccion.setText(direccion);
        cTelefono.setText(telefono);
        cCel.setText(celular);
        cCorreo.setText(correo);
    }

    @Action public void closeAboutBox() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        eNombre = new javax.swing.JLabel();
        cNombre = new javax.swing.JTextField();
        cApellido = new javax.swing.JTextField();
        lala = new javax.swing.JLabel();
        eCelular = new javax.swing.JLabel();
        cCel = new javax.swing.JTextField();
        cTelefono = new javax.swing.JTextField();
        eTel = new javax.swing.JLabel();
        eDireccion = new javax.swing.JLabel();
        cDireccion = new javax.swing.JTextField();
        cCorreo = new javax.swing.JTextField();
        eCorreo = new javax.swing.JLabel();
        eCobrador = new javax.swing.JLabel();
        lCobrador = new javax.swing.JComboBox();
        ePlan = new javax.swing.JLabel();
        cCuotas = new javax.swing.JTextField();
        cMonto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cACaja = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(style.StyleApp.class).getContext().getResourceMap(NuevoPlan.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(300, 79));
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(style.StyleApp.class).getContext().getActionMap(NuevoPlan.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N

        botonAceptar.setText(resourceMap.getString("botonAceptar.text")); // NOI18N
        botonAceptar.setName("botonAceptar"); // NOI18N
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        eNombre.setText(resourceMap.getString("eNombre.text")); // NOI18N
        eNombre.setName("eNombre"); // NOI18N

        cNombre.setEditable(false);
        cNombre.setText(resourceMap.getString("cNombre.text")); // NOI18N
        cNombre.setName("cNombre"); // NOI18N

        cApellido.setEditable(false);
        cApellido.setName("cApellido"); // NOI18N

        lala.setText(resourceMap.getString("lala.text")); // NOI18N
        lala.setName("lala"); // NOI18N

        eCelular.setText(resourceMap.getString("eCelular.text")); // NOI18N
        eCelular.setName("eCelular"); // NOI18N

        cCel.setEditable(false);
        cCel.setName("cCel"); // NOI18N

        cTelefono.setEditable(false);
        cTelefono.setName("cTelefono"); // NOI18N

        eTel.setText(resourceMap.getString("eTel.text")); // NOI18N
        eTel.setName("eTel"); // NOI18N

        eDireccion.setText(resourceMap.getString("eDireccion.text")); // NOI18N
        eDireccion.setName("eDireccion"); // NOI18N

        cDireccion.setEditable(false);
        cDireccion.setName("cDireccion"); // NOI18N

        cCorreo.setEditable(false);
        cCorreo.setName("cCorreo"); // NOI18N

        eCorreo.setText(resourceMap.getString("eCorreo.text")); // NOI18N
        eCorreo.setName("eCorreo"); // NOI18N

        eCobrador.setText(resourceMap.getString("eCobrador.text")); // NOI18N
        eCobrador.setName("eCobrador"); // NOI18N

        lCobrador.setName("lCobrador"); // NOI18N

        ePlan.setText(resourceMap.getString("ePlan.text")); // NOI18N
        ePlan.setName("ePlan"); // NOI18N

        cCuotas.setText(resourceMap.getString("cCuotas.text")); // NOI18N
        cCuotas.setName("cCuotas"); // NOI18N

        cMonto.setText(resourceMap.getString("cMonto.text")); // NOI18N
        cMonto.setName("cMonto"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        cACaja.setText(resourceMap.getString("cACaja.text")); // NOI18N
        cACaja.setName("cACaja"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(eNombre)
                        .addGap(10, 10, 10)
                        .addComponent(cNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lala)
                        .addGap(10, 10, 10)
                        .addComponent(cApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(eCelular)
                        .addGap(10, 10, 10)
                        .addComponent(cCel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(eTel)
                        .addGap(10, 10, 10)
                        .addComponent(cTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(eDireccion)
                        .addGap(10, 10, 10)
                        .addComponent(cDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(eCorreo)
                        .addGap(10, 10, 10)
                        .addComponent(cCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eCobrador)
                            .addComponent(ePlan))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonAceptar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(1, 1, 1)))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cACaja, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(closeButton))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(eNombre))
                    .addComponent(cNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lala))
                    .addComponent(cApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(eCelular))
                    .addComponent(cCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(eTel))
                    .addComponent(cTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(eDireccion))
                    .addComponent(cDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(eCorreo))
                    .addComponent(cCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(eCobrador))
                    .addComponent(lCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(ePlan)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAceptar)
                            .addComponent(closeButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(cMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cACaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))))
        );

        BCobradores cobrador = new BCobradores();
        cobrador.ConectarSQL();
        try {
            cobrador.getNombreApellido(lCobrador);
        }catch (SQLException ex ){lCobrador.addItem("Error");}
        cobrador.CerrarSQL();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
    BClientes cliente = new BClientes ();
    BCobradores cobradores = new BCobradores ();
    BCuotas cuotas = new BCuotas ();
    BDeuda deuda = new BDeuda ();
    BPago pago = new BPago ();
    BCaja caja = new BCaja ();
    String boludez = (String) lCobrador.getSelectedItem();
    String[] arr = new String [2];
    arr = boludez.split(" ");

    cliente.ConectarSQL();
    cobradores.ConectarSQL();
    cuotas.ConectarSQL();
    deuda.ConectarSQL();
    pago.ConectarSQL();
    caja.ConectarSQL();

        try {
            deuda.crearDeuda((Double.valueOf(cMonto.getText()))*(Integer.valueOf(cCuotas.getText())), Integer.valueOf(cCuotas.getText()), cliente.getIdFromNomAp(cNombre.getText(), cApellido.getText()));
            cuotas.insertarCuotas(Integer.valueOf(cCuotas.getText()), deuda.fechaGenerada(deuda.getIdDeudas(cliente.getIdFromNomAp(cNombre.getText(), cApellido.getText()))), Double.valueOf(cMonto.getText()), deuda.getIdDeudas(cliente.getIdFromNomAp(cNombre.getText(), cApellido.getText())));
            pago.agregarPago(cliente.getIdFromNomAp(cNombre.getText(),cApellido.getText()),deuda.getIdDeudas(cliente.getIdFromNomAp(cNombre.getText(), cApellido.getText())), 0, deuda.fechaGenerada(deuda.getIdDeudas(cliente.getIdFromNomAp(cNombre.getText(), cApellido.getText()))), cobradores.getIdFromNomAp(arr[0], arr[1]));
            caja.insertarEgreso("Prestamo a "+cNombre.getText() + " "+cApellido.getText(), Double.valueOf(cACaja.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(CargaContacto.class.getName()).log(Level.SEVERE, null, ex);
        }

    cliente.CerrarSQL();
    cobradores.CerrarSQL();
    cuotas.CerrarSQL();
    deuda.CerrarSQL();
    pago.CerrarSQL();
    caja.CerrarSQL();

    dispose();
    }//GEN-LAST:event_botonAceptarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JTextField cACaja;
    private javax.swing.JTextField cApellido;
    private javax.swing.JTextField cCel;
    private javax.swing.JTextField cCorreo;
    private javax.swing.JTextField cCuotas;
    private javax.swing.JTextField cDireccion;
    private javax.swing.JTextField cMonto;
    private javax.swing.JTextField cNombre;
    private javax.swing.JTextField cTelefono;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel eCelular;
    private javax.swing.JLabel eCobrador;
    private javax.swing.JLabel eCorreo;
    private javax.swing.JLabel eDireccion;
    private javax.swing.JLabel eNombre;
    private javax.swing.JLabel ePlan;
    private javax.swing.JLabel eTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox lCobrador;
    private javax.swing.JLabel lala;
    // End of variables declaration//GEN-END:variables
    
}
